name       : perl-log-dispatch
version    : '2.71'
release    : 3
source     :
    - https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/Log-Dispatch-2.71.tar.gz : 9d60d9648c35ce2754731eb4deb7f05809ece1bd633b74d74795aed9ec732570
homepage   : https://metacpan.org/pod/Log::Dispatch
license    : Artistic-2.0
component  : programming.perl
summary    : Dispatches messages to one or more outputs
description: |
    This module manages a set of Log::Dispatch::* output objects that can be logged to via a unified interface.
builddeps  :
    - perl-devel-globaldestruction
    - perl-dist-checkconflicts
    - perl-ipc-run3
    - perl-module-runtime
    - perl-namespace-autoclean
    - perl-params-validate
    - perl-params-validationcompiler
    - perl-specio-exporter
    - perl-test-needs
rundeps    :
    - perl-devel-globaldestruction
    - perl-dist-checkconflicts
    - perl-ipc-run3
    - perl-module-runtime
    - perl-namespace-autoclean
    - perl-params-validate
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %make test
