name       : perl-log-dispatch
version    : '2.70'
release    : 2
source     :
    - https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/Log-Dispatch-2.70.tar.gz : a3d91cc52467d3a3c6683103f3df4472d71e405a45f553289448713ac4293f21
license    : Artistic-2.0
component  : programming.perl
summary    : Dispatches messages to one or more outputs
description: |
    This module manages a set of Log::Dispatch::* output objects that can be logged to via a unified interface.
builddeps  :
    - perl-devel-globaldestruction
    - perl-dist-checkconflicts
    - perl-ipc-run3
    - perl-module-runtime
    - perl-namespace-autoclean
    - perl-params-validate
    - perl-params-validationcompiler
    - perl-specio-exporter
    - perl-test-needs
rundeps    :
    - perl-devel-globaldestruction
    - perl-dist-checkconflicts
    - perl-ipc-run3
    - perl-module-runtime
    - perl-namespace-autoclean
    - perl-params-validate
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %make test
